version: "2"
services:
  mysql:
    image: "mysql:5"
    volumes:
     - ./mysql:/var/lib/mysql
     - ./data:/data
     - ./output:/var/lib/mysql-files
    networks:
     - mysql_conn
    ports:
     - "127.0.0.1:3306:3306"
    env_file: .env
  dtd2mysql:
    build: ./dtd2mysql
    env_file: .env
    networks:
    - mysql_conn
    volumes:
     - ./data:/data

networks:
  mysql_conn:
    driver: bridge
